name: Use GitHub Models

on: [push]

permissions:
  models: read

jobs:
  call-model:
    runs-on: ubuntu-latest
    steps:
      - name: Call AI model
        env:
          GITHUB_TOKEN: ${{ secrets.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}}
        run: |
          curl "https://models.github.ai/inference/chat/completions" \
             -H "Content-Type: application/json" \
             -H "Authorization: Bearer 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" \
             -d '{
              "messages": [
                  {
                     "role": "user",
                     "content": "Explain the concept of recursion."
                  }
               ],
               "model": "openai/gpt-4o"
            }'
